/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "AdjustMarmalade.h"


#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
// For MIPs (and WP8) platform we do not have asm code for stack switching
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL_LOCK
#endif
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*AppDidLaunch_t)(const char* appToken, const char* environment, const char* sdkPrefix, const char* logLevel, bool eventBuffering);
typedef  s3eResult(*TrackEvent_t)(const char* eventToken, const param_type* params);
typedef  s3eResult(*TrackEventIphone_t)(const char* eventToken, const char** params_array, int param_size);
typedef  s3eResult(*TrackRevenue_t)(double cents, const char* eventToken, const param_type* params);
typedef  s3eResult(*TrackRevenueIphone_t)(double cents, const char* eventToken, const char** params_array, int param_size);
typedef  s3eResult(*SetEnabled_t)(bool enabled);
typedef  s3eResult(*IsEnabled_t)(bool& isEnabled_out);
typedef  s3eResult(*SetResponseDelegate_t)(response_data_delegate delegateFn);

/**
 * struct that gets filled in by AdjustMarmaladeRegister
 */
typedef struct AdjustMarmaladeFuncs
{
    AppDidLaunch_t m_AppDidLaunch;
    TrackEvent_t m_TrackEvent;
    TrackEventIphone_t m_TrackEventIphone;
    TrackRevenue_t m_TrackRevenue;
    TrackRevenueIphone_t m_TrackRevenueIphone;
    SetEnabled_t m_SetEnabled;
    IsEnabled_t m_IsEnabled;
    SetResponseDelegate_t m_SetResponseDelegate;
} AdjustMarmaladeFuncs;

static AdjustMarmaladeFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x1066434, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: AdjustMarmalade");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x1066434, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool AdjustMarmaladeAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult AppDidLaunch(const char* appToken, const char* environment, const char* sdkPrefix, const char* logLevel, bool eventBuffering)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[0] func: AppDidLaunch"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_AppDidLaunch(appToken, environment, sdkPrefix, logLevel, eventBuffering);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult TrackEvent(const char* eventToken, const param_type* params)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[1] func: TrackEvent"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_TrackEvent(eventToken, params);

    if (ret == 1) {
        if (params == NULL) {
            ret = g_Ext.m_TrackEventIphone(eventToken, NULL, 0);
        } else {
            param_type::size_type param_size = params->size();;
            const char *params_array[param_size * 2];
            for(param_type::size_type i = 0; i < param_size; i++) {
                const char * key = ((*params)[i]).first;
                params_array[i*2 + 0] = key;

                const char * value = ((*params)[i]).second;
                params_array[i*2 + 1] = value;
            }
            ret = g_Ext.m_TrackEventIphone(eventToken, params_array, param_size);
        }
    }


#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult TrackEventIphone(const char* eventToken, const char** params_array, int param_size)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[2] func: TrackEventIphone"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_TrackEventIphone(eventToken, params_array, param_size);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult TrackRevenue(double cents, const char* eventToken, const param_type* params)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[3] func: TrackRevenue"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_TrackRevenue(cents, eventToken, params);

    if (ret == 1) {
        if (params == NULL) {
            ret = g_Ext.m_TrackRevenueIphone(cents, eventToken, NULL, 0);
        } else {
            param_type::size_type param_size = params->size();;
            const char *params_array[param_size * 2];
            for(param_type::size_type i = 0; i < param_size; i++) {
                const char * key = ((*params)[i]).first;
                params_array[i*2 + 0] = key;

                const char * value = ((*params)[i]).second;
                params_array[i*2 + 1] = value;
            }
            ret = g_Ext.m_TrackRevenueIphone(cents, eventToken, params_array, param_size);
        }
    }


#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult TrackRevenueIphone(double cents, const char* eventToken, const char** params_array, int param_size)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[4] func: TrackRevenueIphone"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_TrackRevenueIphone(cents, eventToken, params_array, param_size);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult SetEnabled(bool enabled)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[5] func: SetEnabled"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_SetEnabled(enabled);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult IsEnabled(bool& isEnabled_out)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[6] func: IsEnabled"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_IsEnabled(isEnabled_out);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult SetResponseDelegate(response_data_delegate delegateFn)
{
    IwTrace(ADJUSTMARMALADE_VERBOSE, ("calling AdjustMarmalade[7] func: SetResponseDelegate"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_SetResponseDelegate(delegateFn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}
