/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ADJUSTMARMALADE_AUTODEFS_H
#define ADJUSTMARMALADE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADJUSTMARMALADE_NAME "AdjustMarmalade"
#define S3E_EXT_ADJUSTMARMALADE_HASH 0x1066434

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("AdjustMarmalade", 18)
#else

#include "s3eEdk.h"

#define ADJUSTMARMALADEGLOBALS ((AdjustMarmaladeGlobals*)s3eEdkGlobalsGet(S3E_EXT_ADJUSTMARMALADE_HASH))
#endif /* S3E_EXT_REGISTER */
#endif /* !ADJUSTMARMALADE_AUTODEFS_H */
